"""Emit figures/data.tex from data/results.json (and optional sidecars).

The paper imports this file with \input{figures/data.tex} and reads the
plot data from macros. This keeps all figures inline in LaTeX (pgfplots)
while letting the analysis script populate them post-experiment.

Macros emitted:
  \dosesAggLZero ... \dosesAggLThree   : aggregate truth-aligned mean per level
  \dosesAggSEZero ... \dosesAggSEThree : SE per level
  \dosesRefLZero ... \dosesRefLThree   : rational reference values
  \perModelCurves                       : pgfplots-friendly per-model coords block
  \slopeBrierPoints                     : pgfplots scatter coords + labels
  \slopeDistReasoning, \slopeDistNonReasoning : whisker stats per group
  \nQuestions, \nModels, \pearsonR, \pearsonP, \mannWhitneyP, etc.
"""
from __future__ import annotations
import json
from pathlib import Path

import numpy as np

from config import RESULTS, FIGS, LEVELS


def _f(x, fmt="{:.3f}"):
    if x is None or (isinstance(x, float) and (x != x)):
        return "?"
    return fmt.format(x)


def _level_idx_macro(i):
    # 0,1,2,3 -> Zero, One, Two, Three
    return ["Zero", "One", "Two", "Three"][i]


def _short(name: str) -> str:
    """Strip the redundant 'Claude ' brand prefix from Anthropic model names."""
    if name and name.startswith("Claude "):
        return name[len("Claude "):]
    return name


def main():
    r = json.loads(Path(RESULTS).read_text())
    out = []
    out.append("% Auto-generated by code/emit_data_tex.py — DO NOT EDIT BY HAND.")
    out.append("% Re-run `python code/emit_data_tex.py` after `python run.py`.")

    # Aggregate per-level
    agg = r.get("aggregate_aligned_by_level", {})
    means = []
    for i, lvl in enumerate(LEVELS):
        v = agg.get(lvl, {})
        m = v.get("mean")
        se = v.get("se", 0.0)
        means.append(m if m is not None else 0.5)
        out.append(rf"\def\dosesAggL{_level_idx_macro(i)}{{{_f(m)}}}")
        out.append(rf"\def\dosesAggSEL{_level_idx_macro(i)}{{{_f(se)}}}")
    # Rational reference: prior at L0 + (1-prior)*i/3
    base = means[0] if means else 0.5
    for i in range(len(LEVELS)):
        ref = base + (1.0 - base) * i / (len(LEVELS) - 1)
        out.append(rf"\def\dosesRefL{_level_idx_macro(i)}{{{_f(ref)}}}")

    # Aggregate dose-response coords as a single macro
    agg_coords = " ".join(
        f"({i},{_f(agg.get(lvl, {}).get('mean'))})" for i, lvl in enumerate(LEVELS)
    )
    out.append(rf"\def\dosesAggCoords{{{agg_coords}}}")
    ref_coords = " ".join(
        f"({i},{_f(base + (1.0 - base) * i / (len(LEVELS) - 1))})" for i in range(len(LEVELS))
    )
    out.append(rf"\def\dosesRefCoords{{{ref_coords}}}")

    # Per-model curves: emit one \addplot block per model as a single macro.
    pm_curves = r.get("per_model_curves", {})
    pm_meta = r.get("models", {})
    blocks = []
    for api_id, lvls in pm_curves.items():
        meta = pm_meta.get(api_id, {})
        coords = " ".join(f"({i},{_f(lvls.get(l))})" for i, l in enumerate(LEVELS))
        style = "reasoning" if meta.get("reasoning") else "nonreasoning"
        label = _short(meta.get("display", api_id)).replace("_", " ")
        blocks.append(
            r"\addplot+[" + style + r",mark=*,thick] coordinates {" + coords + r"};"
            r"\addlegendentry{" + label + (" (R)" if meta.get("reasoning") else "") + r"}"
        )
    out.append(r"\def\perModelPlots{" + "\n".join(blocks) + r"}")

    # Slope-vs-Brier scatter
    pts = []
    labels = []
    for api_id, m in pm_meta.items():
        s = m.get("mean_slope")
        b = m.get("brier_L3")
        if s is None or b is None:
            continue
        c = "reasoningmark" if m.get("reasoning") else "nonreasoningmark"
        pts.append(f"\\addplot+[only marks,{c}] coordinates {{({_f(s)},{_f(b)})}};")
        pts.append(
            r"\node[font=\tiny] at (axis cs:" + f"{_f(s)},{_f(b)}" + r") "
            r"[anchor=south west,xshift=2pt,yshift=2pt] {" + _short(m.get("display", api_id)) + "};"
        )
        labels.append(_short(m.get("display", api_id)))
    out.append(r"\def\slopeBrierPlots{" + "\n".join(pts) + r"}")

    # Slope distribution boxplot data: just emit the per-question slopes for
    # reasoning vs non-reasoning groups.
    by_group = {"reasoning": [], "non": []}
    for key, val in r.get("per_question", {}).items():
        api_id = key.split("__", 1)[0]
        meta = pm_meta.get(api_id, {})
        grp = "reasoning" if meta.get("reasoning") else "non"
        s = val.get("slope")
        if s is not None:
            by_group[grp].append(s)
    for grp in ("reasoning", "non"):
        vals = sorted(by_group[grp])
        if vals:
            q1 = float(np.percentile(vals, 25))
            med = float(np.percentile(vals, 50))
            q3 = float(np.percentile(vals, 75))
            iqr = q3 - q1
            lo = max(min(vals), q1 - 1.5 * iqr)
            hi = min(max(vals), q3 + 1.5 * iqr)
        else:
            q1 = med = q3 = lo = hi = 0.0
        suffix = grp.capitalize() if grp == "reasoning" else "Non"
        out.append(rf"\def\slopeBox{suffix}LowerWhisker{{{_f(lo)}}}")
        out.append(rf"\def\slopeBox{suffix}LowerQuartile{{{_f(q1)}}}")
        out.append(rf"\def\slopeBox{suffix}Median{{{_f(med)}}}")
        out.append(rf"\def\slopeBox{suffix}UpperQuartile{{{_f(q3)}}}")
        out.append(rf"\def\slopeBox{suffix}UpperWhisker{{{_f(hi)}}}")

    # Top-line numbers
    sb = r.get("slope_brier_correlation", {})
    rv = r.get("reasoning_vs_non", {})
    bl = r.get("brier_l0_l3_correlation", {})
    pp = r.get("slope_brier_partial_r", {})
    vd = r.get("variance_decomposition", {})
    n_q = len({k.split("__", 1)[1] for k in r.get("per_question", {}).keys()}) or 0
    n_m = len(pm_meta)
    out.append(rf"\def\nQuestions{{{n_q}}}")
    out.append(rf"\def\nModels{{{n_m}}}")
    out.append(rf"\def\pearsonR{{{_f(sb.get('pearson_r'))}}}")
    out.append(rf"\def\pearsonP{{{_f(sb.get('p_value'), '{:.3g}')}}}")
    out.append(rf"\def\partialR{{{_f(pp.get('partial_r'))}}}")
    out.append(rf"\def\brierLzeroLthreeR{{{_f(bl.get('pearson_r'))}}}")
    out.append(rf"\def\brierLzeroLthreeP{{{_f(bl.get('p_value'), '{:.3g}')}}}")
    out.append(rf"\def\mannWhitneyP{{{_f(rv.get('p_value'), '{:.3g}')}}}")
    out.append(rf"\def\meanSlopeReasoning{{{_f(rv.get('mean_slope_reasoning'))}}}")
    out.append(rf"\def\meanSlopeNonReasoning{{{_f(rv.get('mean_slope_non_reasoning'))}}}")
    out.append(rf"\def\fracQuestionVar{{{_f(vd.get('frac_question'), '{:.3f}')}}}")
    out.append(rf"\def\fracModelVar{{{_f(vd.get('frac_model'), '{:.3f}')}}}")
    out.append(rf"\def\fracQuestionVarPct{{{_f((vd.get('frac_question') or 0) * 100, '{:.1f}')}}}")
    out.append(rf"\def\fracModelVarPct{{{_f((vd.get('frac_model') or 0) * 100, '{:.1f}')}}}")

    # Aggregate captured-gain fraction: (L3 - L0) / (1 - L0)
    a0 = r["aggregate_aligned_by_level"].get("L0", {}).get("mean")
    a3 = r["aggregate_aligned_by_level"].get("L3", {}).get("mean")
    if a0 is not None and a3 is not None and (1 - a0) > 0:
        captured = (a3 - a0) / (1 - a0)
        out.append(rf"\def\fracRationalGain{{{_f(captured)}}}")
        out.append(rf"\def\fracRationalGainPct{{{_f(captured * 100, '{:.1f}')}}}")

    # Per-model update efficiency: fraction of headroom closed L0 -> L3.
    eff = r.get("per_model_update_efficiency", {})

    # Per-model table rows: now includes update efficiency.
    rows = []
    sorted_models = sorted(pm_meta.items(),
                          key=lambda kv: -((eff.get(kv[0]) or 0.0)))
    for api_id, m in sorted_models:
        rows.append(
            " & ".join([
                _short(m.get("display", api_id)),
                "Yes" if m.get("reasoning") else "No",
                _f(m.get("brier_L0")),
                _f(m.get("brier_L3")),
                _f(m.get("mean_slope")),
                _f(eff.get(api_id)),
            ]) + r" \\"
        )
    out.append(r"\def\perModelTableRows{" + "\n".join(rows) + r"}")

    # Brier-L0 vs Brier-L3 scatter coords + OLS regression endpoints.
    bl_pts = []
    xs, ys = [], []
    for api_id, m in pm_meta.items():
        if m.get("brier_L0") is None or m.get("brier_L3") is None:
            continue
        x, y = m["brier_L0"], m["brier_L3"]
        xs.append(x); ys.append(y)
        c = "reasoningmark" if m.get("reasoning") else "nonreasoningmark"
        bl_pts.append(
            f"\\addplot+[only marks,{c}] coordinates {{({_f(x)},{_f(y)})}};"
        )
        # Per-model label placement overrides (avoids overlap; matches the
        # hand-tuned camera-ready figure).
        _anchor = {
            "Sonnet 4.6": "anchor=south west,xshift=3pt,yshift=1pt",
            "o3": "anchor=north east,xshift=-3pt,yshift=-1pt",
        }.get(_short(m.get("display", api_id)), "anchor=north west,xshift=2pt,yshift=-2pt")
        bl_pts.append(
            r"\node[font=\tiny] at (axis cs:"
            f"{_f(x)},{_f(y)}"
            f") [{_anchor}] {{"
            f"{_short(m.get('display', api_id))}" + r"};"
        )
    out.append(r"\def\brierLoLthreePlots{" + "\n".join(bl_pts) + r"}")
    # OLS regression line endpoints for the scatter.
    if len(xs) >= 2:
        import numpy as _np
        xs_a, ys_a = _np.array(xs), _np.array(ys)
        beta, alpha = _np.polyfit(xs_a, ys_a, 1)
        # Extend the line a touch beyond the data range so it visibly spans the axes.
        x_lo = float(xs_a.min()) - 0.005
        x_hi = float(xs_a.max()) + 0.005
        y_lo, y_hi = float(alpha + beta * x_lo), float(alpha + beta * x_hi)
        out.append(
            rf"\def\brierLoLthreeFit{{({_f(x_lo)},{_f(y_lo)}) ({_f(x_hi)},{_f(y_hi)})}}"
        )

    # ---------- Robustness macros (R1, R2, R3, R4) ----------
    rb = r.get("robustness", {}) or {}
    bs = rb.get("bootstrap", {}) or {}
    for name, key in [
        ("BootSlopeBrier", "slope_vs_brierL3"),
        ("BootPriorBrier", "brierL0_vs_brierL3"),
        ("BootPartial",    "partial_slope_brierL3_given_brierL0"),
    ]:
        v = bs.get(key, {}) or {}
        out.append(rf"\def\{name}Mean{{{_f(v.get('mean'))}}}")
        out.append(rf"\def\{name}Lo{{{_f(v.get('lo95'))}}}")
        out.append(rf"\def\{name}Hi{{{_f(v.get('hi95'))}}}")

    re_ = rb.get("random_effects", {}) or {}
    out.append(rf"\def\reVarQuestion{{{_f(re_.get('var_question'), '{:.4f}')}}}")
    out.append(rf"\def\reVarModel{{{_f(re_.get('var_model'), '{:.4f}')}}}")
    out.append(rf"\def\reVarResidual{{{_f(re_.get('var_residual'), '{:.4f}')}}}")
    out.append(rf"\def\reFracQuestion{{{_f(re_.get('frac_question'), '{:.3f}')}}}")
    out.append(rf"\def\reFracQuestionPct{{{_f((re_.get('frac_question') or 0) * 100, '{:.1f}')}}}")
    out.append(rf"\def\reFracModel{{{_f(re_.get('frac_model'), '{:.3f}')}}}")
    out.append(rf"\def\reFracModelPct{{{_f((re_.get('frac_model') or 0) * 100, '{:.1f}')}}}")

    cm = rb.get("contamination", {}) or {}
    out.append(rf"\def\contamR{{{_f(cm.get('pearson_r_brierL0_vs_resolveTime'))}}}")
    out.append(rf"\def\contamP{{{_f(cm.get('pearson_p'), '{:.3g}')}}}")
    out.append(rf"\def\contamEarlyBrier{{{_f(cm.get('early_brier_L0_mean'))}}}")
    out.append(rf"\def\contamLateBrier{{{_f(cm.get('late_brier_L0_mean'))}}}")
    out.append(rf"\def\contamNearly{{{cm.get('early_n_questions', '?')}}}")
    out.append(rf"\def\contamNlate{{{cm.get('late_n_questions', '?')}}}")

    ma = rb.get("manifold_anchor", {}) or {}
    out.append(rf"\def\manifoldCapture{{{_f(ma.get('median_capture_ratio'))}}}")
    ci = ma.get("median_ci95") or [None, None]
    out.append(rf"\def\manifoldCaptureLo{{{_f(ci[0])}}}")
    out.append(rf"\def\manifoldCaptureHi{{{_f(ci[1])}}}")
    out.append(rf"\def\manifoldCapturePct{{{_f((ma.get('median_capture_ratio') or 0) * 100, '{:.1f}')}}}")
    out.append(rf"\def\manifoldNquestions{{{ma.get('n_questions_with_anchor', '?')}}}")
    out.append(rf"\def\manifoldNpairs{{{ma.get('n_pairs_for_capture', '?')}}}")

    # ---------- Robustness v2 macros (referee response) ----------
    rb2 = rb.get("v2", {}) or {}

    # S1: marginal vs total Manifold ratios
    manv2 = rb2.get("manifold", {}) or {}
    tot = manv2.get("total_ratio") or {}
    mar = manv2.get("marginal_ratio") or {}
    out.append(rf"\def\manifoldTotalMedian{{{_f(tot.get('median'))}}}")
    out.append(rf"\def\manifoldTotalLo{{{_f(tot.get('lo95'))}}}")
    out.append(rf"\def\manifoldTotalHi{{{_f(tot.get('hi95'))}}}")
    out.append(rf"\def\manifoldTotalN{{{tot.get('n', '?')}}}")
    out.append(rf"\def\manifoldMargMedian{{{_f(mar.get('median'))}}}")
    out.append(rf"\def\manifoldMargLo{{{_f(mar.get('lo95'))}}}")
    out.append(rf"\def\manifoldMargHi{{{_f(mar.get('hi95'))}}}")
    out.append(rf"\def\manifoldMargN{{{mar.get('n', '?')}}}")
    out.append(rf"\def\manifoldMargPct{{{_f((mar.get('median') or 0) * 100, '{:.1f}')}}}")

    # S2: single crossed random-effects
    cre = rb2.get("crossed_re", {}) or {}
    out.append(rf"\def\creVarQuestion{{{_f(cre.get('var_question'), '{:.4f}')}}}")
    out.append(rf"\def\creVarModel{{{_f(cre.get('var_model'), '{:.4f}')}}}")
    out.append(rf"\def\creVarResidual{{{_f(cre.get('var_residual'), '{:.4f}')}}}")
    out.append(rf"\def\creFracQuestionPct{{{_f((cre.get('frac_question') or 0) * 100, '{:.1f}')}}}")
    out.append(rf"\def\creFracModelPct{{{_f((cre.get('frac_model') or 0) * 100, '{:.1f}')}}}")
    out.append(rf"\def\creRatioQM{{{_f(cre.get('ratio_question_over_model'), '{:.0f}')}}}")

    # S3: DRR
    drr = rb2.get("drr", {}) or {}
    out.append(rf"\def\drrCoef{{{_f(drr.get('ols_coef_sqrt_brier_L0'))}}}")
    pm_drr = drr.get("per_model", {}) or {}
    # Per-model DRR table rows, sorted by DRR descending.
    rows_drr = []
    for api_id, v in sorted(pm_drr.items(), key=lambda kv: -kv[1]["DRR"]):
        rows_drr.append(
            " & ".join([
                _short(v.get("display", api_id)),
                "Yes" if v.get("reasoning") else "No",
                _f(v.get("slope"), "{:.4f}"),
                _f(v.get("predicted_slope_from_prior"), "{:.4f}"),
                _f(v.get("DRR"), "{:.4f}"),
            ]) + r" \\"
        )
    out.append(r"\def\drrTableRows{" + "\n".join(rows_drr) + r"}")

    # Per-model marginal/total Manifold capture rows.
    pm_tot = manv2.get("per_model_total_median", {}) or {}
    pm_mar = manv2.get("per_model_marginal_median", {}) or {}
    pm_meta_all = r.get("models", {})
    rows_cap = []
    for api_id in pm_meta_all.keys():
        meta = pm_meta_all[api_id]
        rows_cap.append(
            " & ".join([
                _short(meta.get("display", api_id)),
                "Y" if meta.get("reasoning") else "N",
                _f(pm_tot.get(api_id), "{:.3f}") if pm_tot.get(api_id) is not None else "--",
                _f(pm_mar.get(api_id), "{:.3f}") if pm_mar.get(api_id) is not None else "--",
            ]) + r" \\"
        )
    out.append(r"\def\manifoldCaptureTableRows{" + "\n".join(rows_cap) + r"}")

    # S4: leave-one-out
    loo = rb2.get("loo_variance", {}) or {}
    out.append(rf"\def\looFracQMin{{{_f((loo.get('frac_question_loo_min') or 0) * 100, '{:.1f}')}}}")
    out.append(rf"\def\looFracQMax{{{_f((loo.get('frac_question_loo_max') or 0) * 100, '{:.1f}')}}}")

    # Hierarchical mixed-effects analysis (clean, mechanical-coupling-free)
    hic = rb.get("hierarchical_clean", {}) or {}
    out.append(rf"\def\hierNcells{{{hic.get('n_cells', '?')}}}")
    for k_label, k_dict in [("Naive", hic.get("naive_subslope", {})),
                            ("Ctrl",  hic.get("controlled_subslope", {}))]:
        fe = (k_dict.get("fixed_effects") or {})
        ss_fe = fe.get("sub_slope_02", {}) or {}
        out.append(rf"\def\hier{k_label}SlopeBeta{{{_f(ss_fe.get('estimate'))}}}")
        out.append(rf"\def\hier{k_label}SlopeSE{{{_f(ss_fe.get('se'), '{:.3f}')}}}")
        out.append(rf"\def\hier{k_label}SlopeT{{{_f(ss_fe.get('t'), '{:.1f}')}}}")
        out.append(rf"\def\hier{k_label}SlopeP{{{_f(ss_fe.get('p'), '{:.2g}')}}}")
        out.append(rf"\def\hier{k_label}SlopeLo{{{_f(ss_fe.get('ci_lo'))}}}")
        out.append(rf"\def\hier{k_label}SlopeHi{{{_f(ss_fe.get('ci_hi'))}}}")
    bL0_fe = ((hic.get("controlled_subslope", {}).get("fixed_effects") or {}).get("brier_L0", {}) or {})
    out.append(rf"\def\hierCtrlPriorBeta{{{_f(bL0_fe.get('estimate'))}}}")
    out.append(rf"\def\hierCtrlPriorT{{{_f(bL0_fe.get('t'), '{:.1f}')}}}")

    # DRR extensions: leaderboard ranks + DRR_Res
    dx = rb.get("drr_extensions", {}) or {}
    out.append(rf"\def\drrResCoef{{{_f(dx.get('drr_res_ols_coef_sqrt_brier_L0'))}}}")
    pair_stats = dx.get("pair_stats", {}) or {}
    _digit_words = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four",
                    "5": "Five", "6": "Six", "7": "Seven", "8": "Eight", "9": "Nine"}
    def _macro_safe(s):
        for d, w in _digit_words.items():
            s = s.replace(d, w)
        return s
    for k_label, k_dict in pair_stats.items():
        suffix = k_label.replace("__vs__", "Vs").replace("_", "").title().replace(" ", "")
        suffix = _macro_safe(suffix)
        out.append(rf"\def\rankTau{suffix}{{{_f(k_dict.get('kendall_tau'))}}}")
        out.append(rf"\def\rankP{suffix}{{{_f(k_dict.get('kendall_p'), '{:.3g}')}}}")

    # DRR_Res leaderboard table rows: sorted by DRR_Res desc. Values only;
    # rank correlations live in the caption.
    leaderboard_rows = []
    for t in (dx.get("table_rows", []) or []):
        leaderboard_rows.append(
            " & ".join([
                _short(t["display"]),
                "Y" if t["reasoning"] else "N",
                _f(t["brier_L3"], "{:.3f}"),
                _f(t["slope"], "{:.3f}"),
                _f(t["DRR_Res"], "{:+.3f}"),
            ]) + r" \\"
        )
    out.append(r"\def\leaderboardRows{" + "\n".join(leaderboard_rows) + r"}")

    # Ladder ablation
    ablation_path = Path(__file__).resolve().parent.parent / "data" / "ladder_ablation.json"
    if ablation_path.exists():
        ab = json.loads(ablation_path.read_text()).get("summary", {}) or {}
        out.append(rf"\def\ablationN{{{ab.get('n_pairs', '?')}}}")
        out.append(rf"\def\ablationOpusLadder{{{_f(ab.get('mean_slope_opus_ladder'), '{:.4f}')}}}")
        out.append(rf"\def\ablationGPTLadder{{{_f(ab.get('mean_slope_gpt5_ladder'), '{:.4f}')}}}")
        out.append(rf"\def\ablationDiff{{{_f(ab.get('mean_diff'), '{:.4f}')}}}")
        out.append(rf"\def\ablationTP{{{_f(ab.get('paired_t_p'), '{:.3g}')}}}")
        out.append(rf"\def\ablationWP{{{_f(ab.get('wilcoxon_p'), '{:.3g}')}}}")

    # Brier decomposition
    bd = rb.get("brier_decomp", {}).get("summary", {}) or {}
    out.append(rf"\def\brierRelReduction{{{_f(bd.get('rel_reduction_mean'), '{:.3f}')}}}")
    out.append(rf"\def\brierResGain{{{_f(bd.get('res_gain_mean'), '{:.3f}')}}}")
    rr = bd.get("rel_L0_vs_L3") or {}
    rs = bd.get("res_L0_vs_L3") or {}
    out.append(rf"\def\brierRelLOLthreeR{{{_f(rr.get('r'))}}}")
    out.append(rf"\def\brierResLOLthreeR{{{_f(rs.get('r'))}}}")

    # Per-model capture bar-chart coords + Brier-decomp bar-chart coords.
    cap_total_coords = []
    cap_marg_coords = []
    rel_red_coords = []
    res_gain_coords = []
    pm_tot = manv2.get("per_model_total_median", {}) or {}
    pm_mar = manv2.get("per_model_marginal_median", {}) or {}
    bd_rows = rb.get("brier_decomp", {}).get("summary", {}).get("per_model", []) or []
    bd_by_model = {row["model"]: row for row in bd_rows}
    _shorten_local = {
        "GPT-5 mini": "5-mini",
        "GPT-4o": "4o",
        "Claude Opus 4.7": "Opus",
        "Claude Sonnet 4.6": "Sonnet",
        "Claude Haiku 4.5": "Haiku",
        "GPT-5": "GPT-5",
        "o3": "o3",
    }
    for i, (api_id, m) in enumerate(pm_meta_all.items()):
        short = _shorten_local.get(_short(m.get("display", api_id)), _short(m.get("display", api_id)))
        if api_id in pm_tot:
            cap_total_coords.append(f"({short},{_f(pm_tot[api_id])})")
        if api_id in pm_mar:
            cap_marg_coords.append(f"({short},{_f(pm_mar[api_id])})")
        if api_id in bd_by_model:
            row = bd_by_model[api_id]
            rel_red_coords.append(f"({short},{_f(row.get('rel_reduction'))})")
            res_gain_coords.append(f"({short},{_f(row.get('res_gain'))})")
    out.append(rf"\def\captureTotalCoords{{{' '.join(cap_total_coords)}}}")
    out.append(rf"\def\captureMargCoords{{{' '.join(cap_marg_coords)}}}")
    out.append(rf"\def\relReductionCoords{{{' '.join(rel_red_coords)}}}")
    out.append(rf"\def\resGainCoords{{{' '.join(res_gain_coords)}}}")
    out.append(r"\def\modelSymbolList{5-mini,4o,Opus,Sonnet,Haiku,GPT-5,o3}")
    # x-tick labels: shortened model names so they fit in a single column.
    _shorten = {
        "GPT-5 mini": "5-mini",
        "GPT-4o": "4o",
        "Claude Opus 4.7": "Opus",
        "Claude Sonnet 4.6": "Sonnet",
        "Claude Haiku 4.5": "Haiku",
        "GPT-5": "GPT-5",
        "o3": "o3",
    }
    tick_labels = ",".join(_shorten.get(_short(m.get("display", api_id)), _short(m.get("display", api_id)))
                           for api_id, m in pm_meta_all.items())
    out.append(rf"\def\modelTickLabels{{{tick_labels}}}")

    # ---- Camera-ready block (from camera_ready_analysis.py) ----
    cr_path = Path(RESULTS).parent / "camera_ready.json"
    if cr_path.exists():
        cr = json.loads(cr_path.read_text())
        out.append("% ---- camera-ready analysis (camera_ready_analysis.py) ----")
        c = cr["cells"]
        out.append(rf"\def\nCellsOrig{{{c['orig_complete']}}}")
        out.append(rf"\def\nCellsBlind{{{c['blind_complete']}}}")
        out.append(rf"\def\nCellsIncomplete{{{c['total'] - c['orig_complete']}}}")
        out.append(rf"\def\nNullRecords{{{c['orig_null_records']}}}")
        h = cr["hierarchical"]
        for key, tex in [("orig_naive", "crOrigNaive"), ("orig_ctrl", "crOrigCtrl"),
                         ("blind_naive", "crBlindNaive"), ("blind_ctrl", "crBlindCtrl"),
                         ("blind_ctrl_common268", "crBlindCommon"),
                         ("orig_ctrl_slope12", "crOrigSlopeTwelve"),
                         ("blind_ctrl_slope12", "crBlindSlopeTwelve")]:
            v = h[key]
            out.append(rf"\def\{tex}Beta{{{v['coef']:.3f}}}")
            out.append(rf"\def\{tex}SE{{{v['se']:.3f}}}")
            out.append(rf"\def\{tex}Lo{{{v['ci_lo']:.3f}}}")
            out.append(rf"\def\{tex}Hi{{{v['ci_hi']:.3f}}}")
        mech = cr["mechanism"]
        out.append(rf"\def\uMean{{{mech['u_mean']:.3f}}}")
        out.append(rf"\def\uSd{{{mech['u_sd']:.3f}}}")
        out.append(rf"\def\uMin{{{mech['u_min']:.3f}}}")
        out.append(rf"\def\uMax{{{mech['u_max']:.3f}}}")
        out.append(rf"\def\KthreeUMean{{{mech['K3_times_u_mean']:.3f}}}")
        out.append(rf"\def\corrUH{{{mech['corr_u_H']:+.2f}}}")
        rows = []
        for r in cr["u_table"]:
            rows.append(f"{_short(r['model'])} & {r['a0']:.3f} & {r['H']:.3f} & "
                        f"{r['slope']:.4f} & {r['u']:.3f} \\\\")
        out.append(r"\def\uTableRows{" + "\n".join(rows) + r"}")
        mono = cr["monotonicity"]
        out.append(rf"\def\cellEpsMedian{{{mono['eps_median']:.3f}}}")
        out.append(rf"\def\cellEpsPninety{{{mono['eps_p90']:.3f}}}")
        out.append(rf"\def\cellEpsMax{{{mono['eps_max']:.3f}}}")
        out.append(rf"\def\fracMonoCells{{{100*mono['frac_weakly_monotone']:.0f}}}")
        comp = cr["comparators"]
        out.append(rf"\def\corrChangeBaseline{{{comp['corr_change_baseline']:+.2f}}}")
        out.append(rf"\def\corrChangeOldham{{{comp['corr_change_oldham_mean']:+.2f}}}")
        out.append(rf"\def\blomqvistObs{{{comp['slope_change_on_baseline_obs']:+.3f}}}")
        out.append(rf"\def\blomqvistCorr{{{comp['blomqvist_corrected_slope']:+.3f}}}")
        out.append(rf"\def\sigmaRatioPct{{{100*comp['measurement_var_sigma_e2']/comp['baseline_var_S2']:.1f}}}")
        b3 = cr["brier_L3_full_precision"]
        out.append(rf"\def\brierLThreeGptFourOFull{{{b3['GPT-4o']:.6f}}}")
        out.append(rf"\def\brierLThreeHaikuFull{{{b3['Claude Haiku 4.5']:.6f}}}")

    FIGS.mkdir(exist_ok=True)
    (FIGS / "data.tex").write_text("\n".join(out) + "\n")
    print(f"wrote {FIGS / 'data.tex'}")


if __name__ == "__main__":
    main()
